-keep class com.zametki.pro.models.** { *; }
-keep class com.zametki.pro.db.** { *; }
-dontwarn javax.annotation.**
-dontwarn kotlin.Unit
-dontwarn retrofit2.KotlinExtensions
-dontwarn retrofit2.KotlinExtensions$*
