-keep class tkm.tmnote.pro.models.** { *; }
-keep class tkm.tmnote.pro.db.** { *; }
-dontwarn javax.annotation.**
-dontwarn kotlin.Unit
-dontwarn retrofit2.KotlinExtensions
-dontwarn retrofit2.KotlinExtensions$*
